# vi mongo-express-nodeport-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-nodeport-svc
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 32000
  selector:
    app: mongodb

