apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-pv

spec:
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 1Gi
  local:
    path: /data/mongo/mongo610
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kworker2

