# vi mongo-express-deploy.yaml
#- name: ME_CONFIG_MONGODB_SERVER
#value: "example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      restartPolicy: Always
      containers:
      - name: mongo-express
        image: mongo-express:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        #- name: ME_CONFIG_MONGODB_SERVER  
        #  valueFrom:
        #    configMapKeyRef:
        #      name: mongodb-configmap
        #      key: mongodb-service
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://admin:password123@mongodb-headless-svc:27017/?authSource=admin" 
        
        - name: PORT
          value: "8081"
        
        - name: ME_CONFIG_SITE_COOKIESECRET
          value: "cookiesecret"
        - name: ME_CONFIG_SITE_SESSIONSECRET
          value: "sessionsecret"    

        - name: ME_CONFIG_BASICAUTH
          value: "true"
 
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        #  valueFrom:
        #    secretKeyRef:
        #      name: mongodb-secret
        #      key: mongodb-admin-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "password123"
        #  valueFrom:
        #    secretKeyRef:
        #      name: mongodb-secret
        #      key: mongodb-admin-password
