apiVersion: v1
kind: Service
metadata:
  name: react-api-service
spec:
  type: ClusterIP
  selector:
    app: react-api

  ports:
  - name: react-api-port
    protocol: TCP
    port: 5000
    targetPort: 5000  