apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-api-deployment
spec:
  replicas: 1

  selector:
    matchLabels:
      app: react-api

  template:
    metadata:
      name: react-api-pod
      labels:
        app: react-api
    spec:
      containers:
      - name: react-api-container
        image: muhdfayyaz/react-api
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_SERVICE
          value: mongodb-service.dev-mongodb.svc.cluster.local
        - name: BACKEND_PORT
          value: 5000
        - name: MONGODB_SCHEMA
          value: react-api
